config/routes.rb
Rails.application.routes.draw do
  resources :letrisms, :equills
  
  devise_for :users, #path: "", :sign_out_via => [ :get ],
    :controllers => { 
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      sessions: 'users/sessions',
      unlocks: 'users/unlocks'
    }

  devise_scope :user do
    get ':lang/sign_up', to: 'users/registrations#new'
    get ':lang/sign_in', to: 'users/sessions#new'
    get ':lang/confirmation', to: 'users/confirmations#new'
    get ':lang/reset_password', to: 'users/passwords#new'
    get ':lang/unlock', to: 'users/unlocks#new'

    get 'crear-cuenta', to: 'users/registrations#new'
    get 'iniciar-sesion', to: 'users/sessions#new'
    get 'confirmar-cuenta', to: 'users/confirmations#new'
    get 'recuperar-cuenta', to: 'users/passwords#new'
    get 'desbloquear-cuenta', to: 'users/unlocks#new'
  end

  # admin
  get 'admin' => 'admin#index', as: :admin  
  namespace :admin do
    resources :users, :ogs, :videos, :images, :pages, :countries, :assets, :letrisms, :equills

    # blog
    get "blog" => "pages#blog", as: :blog
    # user
    get "profile" => "users#profile", as: :profile
    patch "update_profile" => "users#update_profile", as: :update_profile
  end
  
  # data
  get "manifest.json" => "site_info#manifest"

  # sitemaps
  get "sitemap" => "sitemaps#index"
  get "sitemap-static" => "sitemaps#static"
  get "images/sitemap" => "sitemaps#images"
  get "videos/sitemap" => "videos#sitemap"

  scope format: true, constraints: { format: /jpg|png|gif|webp|JPG|JPEG|jpeg/ } do
    get '/*anything', to: "errors#image_not_found"
  end

  scope format: true, constraints: { format: /js/ } do
    get '/*anything', to: "errors#script_not_found"
  end
  # Errors
  # https://guides.rubyonrails.org/v4.2.0/action_controller_overview.html#custom-errors-page
  match "404", via: :all, to: "errors#not_found", as: :not_found
  match "422", via: :all, to: "errors#unprocessable_entity", as: :unprocessable_entity
  match "500", via: :all, to: "errors#server_error", as: :server_error
  match 'offline', via: :all, to: 'errors#offline', as: :offline

  # App
  # root "static#page"
  root 'letrisms#index'

	# get 'manifiesto' => 'static_pages#manifest'
	# get 'galeria' => 'static_pages#gallery'
	# get 'contacto' => 'static_pages#contact'
	# get 'notebook' => 'letrisms#new'
	# get 'notebook/:id' => 'letrisms#new'

  get "mail" => "mailer#mail"
  # get ':lang' => 'static#page', as: :home
  get ':slug' => 'static#page', as: :page
  
end

app/views/admin/pages/_asset_fields.html.erb
<div class="w-full inline-block">
  <div class="grid grid-cols-3 gap-2">
    <div class="w-full">
      <%= object.label :title, t(:title) %>
      <%= object.text_field :title, placeholder: t(:title) %>
    </div>
    <div class="w-full">
      <%= object.label :alt, t(:alt) %>
      <%= object.text_field :alt, placeholder: t(:alt) %>
    </div>
    <div class="w-full">
      <%= object.label :asset_type, t(:asset_type) %>
      <%= object.select :asset_type, [["mp4","Video"],["img","Imagen"],["mp3","audio"]], { include_blank: "Tipo" }, { required: true } %>
    </div>
  </div>

  <div class="col-span-full">
    <label for="cover-photo" class="mt-2">Archivo</label>
    <div class="flex justify-center rounded-lg border border-dashed border-white/25 px-6 py-10">
      <div class="text-center">
        <div class="mt-4 flex text-sm leading-6 text-gray-400">
          <label for="file-upload"
            class="relative transition-colors text-light-500 cursor-pointer rounded-md font-semibold focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 focus-within:ring-offset-gray-900 hover:text-white">
            <i class="fa-solid fa-photo-film text-dark-600 text-4xl pb-2 block"></i>
            <span>Selecciona/Arrastra una imagen o video</span>
          </label>
          <input id="file-upload" name="file-upload" type="file" class="sr-only"
            accept="video/mp4, image/png, image/gif, image/jpeg">
          <%= object.file_field :img, class: "sr-only" %>
          <%= object.file_field :video, class: "sr-only" %>
          <%= object.file_field :audio, class: "sr-only" %>
        </div>
        <p class="text-xs leading-5 text-gray-400">PNG, JPG, GIF, MP4 máximo 10MB</p>
      </div>
    </div>
  </div>
</div>

app/views/admin/pages/_assets.html.erb
<header class="flex items-center justify-between border-b border-white/5 pb-2 md:pb-4">
  <label class="font-medium">Assets</label>
  <%= add_page_asset f %>
</header>

<aside class="w-full inline-block" id="page-assets-container">
  <% idx = 0 %>
  <%= f.fields_for :assets do |asset|  %>
  <%= render "admin/pages/asset_fields", object: asset, idx: idx %>
  <% idx += 1 %>
  <% end %>
</aside>

app/views/admin/pages/_form.html.erb
<section class="content">
  <%= form_for [:admin, page], local: true, html: { :class=> "row" } do |f| %>
  <%= f.hidden_field :category  %>
  <%= render "admin/shared/errors", object: page %>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-2 md:gap-4 lg:gap-6">
    <%= render "admin/pages/og", object: f %>
  </div>

    <!-- /.card-body -->
  <div class="w-full">
    <div class="mt-4">
      <%= f.label :title, class: "m-0 p-0" do  %>
      Título
      <small class="float-right text-dark-500"><i><span id="title-counter"><%= f.object.title.to_s.length %></span> / 70 caracteres</i></small>
      <% end %>
      <%= f.text_field :title, class: "str-counter", placeholder: "Título...", required: true, data: { target: "#title-counter" }, maxLength: 70 %>
    </div>
    <div class="my-2 mb-4">
      <%= f.label :content, "Contenido Principal", class: ""  %>
      <%= f.text_area :content, class: "editor", placeholder: "Contenido", rows: 5, cols: 25 %>
    </div>
  </div>

  <!-- .card-footer/ -->
  <footer class="w-full inline-block">
    <button class="btn btn-outline-primary mt-2 mb-2 btn-sm float-right"><i class="fas fa-save"></i>
      Guardar Cambios</button>
  </footer>
  <% end %>
</section>

app/views/admin/pages/_index.html.erb
<% if object.any? %>
    <% object.each do |page| %>
    <li class="relative flex items-center space-x-4 px-4 py-4 sm:px-6 lg:px-8">
        <div class="min-w-0 flex-auto">
            <a href="/admin/pages/<%= page.id %>/edit" class="flex min-w-0 text-sm font-semibold truncate leading-6"
                title="<%= page.title %>">
                <span class="truncate">
                    <i class="fa-regular fa-circle-dot text-neutral-400 pr-1"></i>
                    <%= page.title %>
                </span>
            </a>
            <div class="mt-3 flex items-center text-xs leading-5 text-neutral-400 whitespace-nowrap">
                Última actualización: <%= l(page.created_at, format: "%d/%B/%Y") %>
            </div>
        </div>
        <%= link_to "/#{page.slug}", class: "btn" do %>
            <i class='fas fa-eye'></i> Vista Previa
        <% end %>
        <%= link_to admin_page_path(page), method: :delete, class: "btn danger" , data: { confirm: "¿Estás seguro de eliminar la página #{page.title}?" } do %>
            <i class='fas fa-trash'></i> Eliminar
        <% end %>
    </li>
    <% end %>
<% else %>
<!--   sin contenido -->
<% end %>

app/views/admin/pages/_og.html.erb
<figure class="p-4 border border-dark-800 bg-primary-900/10 rounded-md shadow-md shadow-dark-800/5 flex flex-col justify-center" id="og-card">
    <%= object.label :og_image do %>
    <%= image_tag object.object.og_image.url, id: "og-img-preview" %>
    <%= object.file_field :og_image, class: "sr-only input-img", data: { target: "#og-img-preview" } %>
    <% end %>
    <h2 class="font-medium mt-1"><span id="page-og-title"><%= object.object.og_title %></span> | <%= "#{Rails.application.credentials.app_name}" %></h2>
    <p id="page-og-description" class="tex-base text-dark-300"><%= object.object.og_description %></p>
    <p id="page-og-link" class="text-dark-500"><%= ENV.fetch('domain') { 'https://juanfuent.es/' } %><span id="page-og-slug"><%= object.object.slug %></span></p>
</figure>

<div class="pt-0">
    <div class="w-full pb-1">
        <%= object.label :og_title, class: "py-4" do %>
        Título
        <small class='legend-validation float-right text-dark-500'><i><span id="og-title-counter"><%= object.object.og_title.to_s.length %></span> / 70 caracteres</i></small>
        <% end %>
        <%= object.text_field :og_title, class: " str-counter input-og-value", placeholder: "Título del artículo sin mencionar marcas", autofocus: true, required: true, data: { target: "#og-title-counter", attr: "title" }, maxLength: 70 %>
    </div>
    <div class="w-full pb-1">
        <%= object.label :slug do %>
        URL Semántica
        <a href="https://es.wikipedia.org/wiki/URL_sem%C3%A1ntica"
            aria-label="Las URL semánticas o URL amigables son aquellas URL que son, dentro de lo que cabe, entendibles para el usuario..."
            data-balloon-pos="up" data-balloon-length="xlarge" target="_blank">
            <i class="fa-solid fa-circle-info"></i>
        </a>
        <div class="mt-2 flex rounded-md shadow-sm">
            <span class="inline-flex items-center rounded-l-md border border-r-0 border-dark-800 h-8 pl-3 text-dark-500 pr-0"><%= ENV.fetch('domain') { 'https://juanfuent.es/' } %></span>
            <%= object.text_field :slug, class: "!p-0 !pl-0 !text-sm !m-0 !rounded-l-none !border-l-0 input-og-value", placeholder: "mi-url-amigable", required: true, data: { attr: "slug" }, readonly: @page.restricted %>
        </div>
        <% end %>
    </div>

    <div class="w-full pb-1">
        <%= object.label :og_description do %>
        Descripción
        <small class='legend-validation float-right text-dark-500'><i><span id="description-counter"><%= object.object.og_description.to_s.length %></span> / 200 caracteres</i></small>
        <% end %>
        <%= object.text_area :og_description, class: " str-counter input-og-value", placeholder: "De 2 a 3 oraciones que describan el contenido sin usar el título.", required: true, data: { target: "#description-counter", attr: "description" }, maxLength: 200 %>
    </div>

    <div class="w-full">
        <%= object.label :keywords %>
        <%= object.text_field :keywords, class: "", placeholder: "keyword, separados, por, coma..." %>
    </div>
</div>

app/views/admin/pages/blog.html.erb
<% provide(:title, "Blog") %>

<!-- Content Header (Page header) -->
<header class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-12">
        <h1>Blog</h1>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</header>

<!-- Main content -->
<section class="content">

  <div class="card card-primary card-outline">
    <header class="card-header">
      <h3 class="card-title">(<%= @pages.count %> artículos)</h3>
      <%= link_to new_admin_page_path(category:'blog'), class: 'btn btn-outline-primary btn-sm float-right' do %>
        <i class="fas fa-plus"></i> Nuevo Artículo
      <% end %>
    </header>
    <div class="card-body p-0">
      <% if @pages.any? %>
        <%= render "admin/pages/table", pages: @pages %>
      <% else %>
        <p class="text-center p-3">Aún no hay artículos creados</p>
      <% end %>
    </div>
  </div>
</section>
<!-- /.content -->

app/views/admin/pages/edit.html.erb
<% provide(:title, "Editando #{@page.title}") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium"><%= "Editando Página: #{@page.title}" %></h1>
    <p class="mt-2 text-gray-500"><%= link_to @page.full_url, @page.full_url, target: "_blank" %> | Idioma <%= t(@page.lang.to_sym) %> | Categoría: <%= @page.category %></p>
  </div>
  <nav class="my-4 sm:flex-none">
    <%= link_to admin_pages_path, class: "btn danger" do %>
      <i class="fa-solid fa-arrow-left"></i> Regresar
    <% end %>
  </nav>
</header>

<%= render 'form', page: @page, remote: false %>

app/views/admin/pages/index.html.erb
<% provide(:title, "Páginas") %>
<!-- header -> -->
<header class="flex items-center justify-between border-b border-white/5 px-4 py-4 sm:px-6 sm:py-6 lg:px-8">
  <h1 class="text-base font-semibold leading-7 text-white">Listado de Páginas <sup><%= @pages.count %></sup></h1>

  <!-- Sort dropdown -->
  <div class="relative">
    <%= link_to new_admin_page_path, class: 'btn success' do %>
    <i class="fas fa-plus"></i> Nueva Página
    <% end %>
  </div>
</header>
<!-- <- header -->

<!-- content -> -->
<ul role="list" class="divide-y divide-white/5">
  <%= render "admin/pages/index", object: @pages %>
</ul>
<!-- <- content -->

app/views/admin/pages/new.html.erb
<% provide(:title, "Nueva Página") %>

<header class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Nueva Página</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right mt-2">
          <li class="breadcrumb-item">
            <%= link_to t(:pages), admin_pages_path %>
          </li>
          <li class="breadcrumb-item active">Nueva Página</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</header>

<%= render 'form', page: @page %>

app/views/admin/pages/show.html.erb
<% provide(:title, "page") %>
<% provide(:image, "") %>
<% provide(:description, "") %>

<header class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= @page.title %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right mt-2">
          <li class="breadcrumb-item">
            <%= link_to t(:pages), admin_pages_path %>
          </li>
          <li class="breadcrumb-item active"><%= @page.title %></li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</header>


<section class="content">
  <!-- Default box -->
  <div class="card card-primary card-outline">
    <div class="card-body">
      <div class="row">
        <article class="col-md-6">
          <%= image_tag @page.image.url %>
          <%= @page.slug %>
        </div>
        <article class="col-md-6">
          <h1><%= @page.title %></h1>
          <p><%= @page.description %></p>
          <p>
          <strong>Keywords:</strong>
          <%= @page.keywords %>
          </p>
          <p>
          <strong>Lang:</strong>
          <%= @page.lang %>
          </p>
          <p>
          <strong>Og type:</strong>
          <%= @page.og_type %>
          </p>
          </article>
      </div>
    </div>
    <!-- /.card-body -->
    <footer class="card-footer">
      <%= link_to edit_admin_page_url(@page), class: "btn btn-outline-primary btn-sm" do %>
        <i class="fas fa-pencil-alt"></i> Editar
      <% end -%>
      <%= link_to t(:delete), admin_page_path(@page), class: "btn btn-outline-danger btn-sm float-right", method: :delete, data: { confirm: "¿Estás seguro de eliminar este #{t(:page)}?" } %>
    </footer>
  </div>
  <!-- /.card -->
</section>