config/routes.rb
Rails.application.routes.draw do
  resources :letrisms, :equills
  
  devise_for :users, #path: "", :sign_out_via => [ :get ],
    :controllers => { 
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      sessions: 'users/sessions',
      unlocks: 'users/unlocks'
    }

  devise_scope :user do
    get ':lang/sign_up', to: 'users/registrations#new'
    get ':lang/sign_in', to: 'users/sessions#new'
    get ':lang/confirmation', to: 'users/confirmations#new'
    get ':lang/reset_password', to: 'users/passwords#new'
    get ':lang/unlock', to: 'users/unlocks#new'

    get 'crear-cuenta', to: 'users/registrations#new'
    get 'iniciar-sesion', to: 'users/sessions#new'
    get 'confirmar-cuenta', to: 'users/confirmations#new'
    get 'recuperar-cuenta', to: 'users/passwords#new'
    get 'desbloquear-cuenta', to: 'users/unlocks#new'
  end

  # admin
  get 'admin' => 'admin#index', as: :admin  
  namespace :admin do
    resources :users, :ogs, :videos, :images, :pages, :countries, :assets, :letrisms, :equills

    # blog
    get "blog" => "pages#blog", as: :blog
    # user
    get "profile" => "users#profile", as: :profile
    patch "update_profile" => "users#update_profile", as: :update_profile
  end
  
  # data
  get "manifest.json" => "site_info#manifest"

  # sitemaps
  get "sitemap" => "sitemaps#index"
  get "sitemap-static" => "sitemaps#static"
  get "images/sitemap" => "sitemaps#images"
  get "videos/sitemap" => "videos#sitemap"

  scope format: true, constraints: { format: /jpg|png|gif|webp|JPG|JPEG|jpeg/ } do
    get '/*anything', to: "errors#image_not_found"
  end

  scope format: true, constraints: { format: /js/ } do
    get '/*anything', to: "errors#script_not_found"
  end
  # Errors
  # https://guides.rubyonrails.org/v4.2.0/action_controller_overview.html#custom-errors-page
  match "404", via: :all, to: "errors#not_found", as: :not_found
  match "422", via: :all, to: "errors#unprocessable_entity", as: :unprocessable_entity
  match "500", via: :all, to: "errors#server_error", as: :server_error
  match 'offline', via: :all, to: 'errors#offline', as: :offline

  # App
  # root "static#page"
  root 'letrisms#index'

	# get 'manifiesto' => 'static_pages#manifest'
	# get 'galeria' => 'static_pages#gallery'
	# get 'contacto' => 'static_pages#contact'
	# get 'notebook' => 'letrisms#new'
	# get 'notebook/:id' => 'letrisms#new'

  get "mail" => "mailer#mail"
  # get ':lang' => 'static#page', as: :home
  get ':slug' => 'static#page', as: :page
  
end

app/models/letrism.rb
class Letrism < ApplicationRecord
	validates_presence_of :img #, :paths
	before_save :set_slug
	belongs_to :equill
	belongs_to :user

	mount_base64_uploader :img, LetrismUploader

	private

	def set_slug
		self.slug = SecureRandom.hex(10) if self.slug.blank?
	end
end

app/controllers/Admin/letrisms_controller.rb
class Admin::LetrismsController < ApplicationController

  before_action :authenticate_admin!
  before_action :set_letrism, only: %i[ show edit update destroy ]

  layout "admin"

  # GET /letrisms
  def index
    @letrisms = Letrism.all
  end

  # GET /letrisms/1
  def show
  end

  # GET /letrisms/new
  def new
    @letrism = Letrism.new
  end

  # GET /letrisms/1/edit
  def edit
  end

  # POST /letrisms
  def create
    @letrism = Letrism.new(letrism_params)

    if @letrism.save
      redirect_to admin_letrisms_url, notice: "Letrism ha sido creado."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /letrisms/1
  def update
    if @letrism.update(letrism_params)
      redirect_to admin_letrisms_url, notice: "Letrism ha sido actualizado."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /letrisms/1
  def destroy
    @letrism.destroy
    redirect_to admin_letrisms_url, notice: "Letrism ha sido eliminado."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_letrism
      @letrism = Letrism.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def letrism_params
      params.require(:letrism).permit(:user_id, :equill_id, :chars, :slug, :paths, :img, :bg, :fill, :stroke, :gallery)
    end
end

app/controllers/letrisms_controller.rb
class LetrismsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_letrism, only: %i[ show edit update destroy ]

  # GET /letrisms
  def index
    @letrisms = Letrism.all.shuffle.take(6)
		@equill = Equill.active.shuffle.first
  end

  # GET /letrisms/1
  def show
    @letrism = Letrism.find_by_slug(params[:id])
  end

  # GET /letrisms/new
  def new
    if params[:id]
			@equill = Equill.find_by_slug(params[:id])
			@letrism = Letrism.new(equill_id: @equill.id)
		else
			redirect_to "/"
		end
  end

  # POST /letrisms
  def create
    @letrism = Letrism.new(letrism_params)
    @letrism.user_id = current_user.id
    if @letrism.save
      redirect_to letrism_path(id: @letrism.slug), notice: "El letrismo ha sido creado."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /letrisms/1
  def update
    if @letrism.update(letrism_params)
      redirect_to admin_letrisms_url, notice: "Letrism ha sido actualizado."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /letrisms/1
  def destroy
    @letrism.destroy
    redirect_to admin_letrisms_url, notice: "Letrism ha sido eliminado."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_letrism
      @letrism = Letrism.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def letrism_params
      params.require(:letrism).permit(:equill_id, :chars, :slug, :paths, :img, :bg, :fill, :stroke, :gallery)
    end

end

app/helpers/letrisms_helper.rb
module LetrismsHelper
end

app/views/letrisms/index.html.erb
<% provide(:title, "#{t(:letrisms)}") %>

<section class="my-8 flow-root">
  <div class="containerGrid">
    <ul>
      <!-- ULTIMO DE LA GALLERIA DE ENTRADA -->
      <li class="description">
        <h1 class="intro-item">
          <img src="/static/equills.svg" alt="eQuills Logo">
        </h1>
        <p class="intro-item">eQuills es el término que adoptamos para referirnos a las herramientas de escritura digital que desarrollamos con el objetivo de dejar marcas imposibles de crear en el mundo físico. Suena bien ¿Cierto? Pruébalo tú mismo.</p>
        <% if @equill.present? %>
        <a href="/notebook/<%= @equill.slug %>" title="Comenzar" class="change-page intro-item"><button>COMENZAR</button></a>
        <% end %>
      </li>
    </ul>
  </div>
</section>

<script>
  var letrisms = [
      <% @letrisms.each do |letrism| %>
        {
          src: `<%= letrism.img.medium.url %>`,
          href: `<%= letrism_path(letrism.slug) %>`,
          author: `<%= letrism.user.username %>`,
        },
      <% end %>
    ]
  var letrismsTotal = <%= @letrisms.count %>
</script>

app/views/letrisms/show.html.erb
<% provide(:title, "letrism") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium"><%= "#{t(:detail)} de #{t(:letrism)}" %></h1>
    <p class="mt-2 text-gray-500">Lorem Ipsum...</p>
  </div>
  <nav class="my-4 sm:flex-none">
    <%= link_to admin_letrisms_path, class: 'btn danger' do %>
      <i class="fa-solid fa-arrow-left"></i> Regresar
    <% end %>
  </nav>
</header>


<section class="content">
  <!-- Default box -->
  <div class="card card-primary card-outline">
    <header class="card-header">
      <%= link_to edit_admin_letrism_url(@letrism), class: "btn btn-outline-primary btn-sm" do %>
        <i class="fas fa-pencil-alt"></i> Editar
      <% end -%>
      <%= link_to admin_letrism_path(@letrism), class: "btn btn-outline-danger btn-sm float-right", method: :delete, data: { confirm: "¿Estás seguro de eliminar este #{t(:letrism)}?" } do %>
        <i class="fa-solid fa-trash"></i> Eliminar
      <% end -%>
    </header>
    <div class="card-body">
      <div class="row">
        <div class="col-12">
                      <p>
              <strong>User:</strong>
                                <%= @letrism.user_id %>
                          </p>
                      <p>
              <strong>Equill:</strong>
                                <%= @letrism.equill_id %>
                          </p>
                      <p>
              <strong>Chars:</strong>
                                <%= @letrism.chars %>
                          </p>
                      <p>
              <strong>Slug:</strong>
                                <%= @letrism.slug %>
                          </p>
                      <p>
              <strong>Paths:</strong>
                                <%= @letrism.paths %>
                          </p>
                      <p>
              <strong>Img:</strong>
                                <%= @letrism.img %>
                          </p>
                      <p>
              <strong>Bg:</strong>
                                <%= @letrism.bg %>
                          </p>
                      <p>
              <strong>Fill:</strong>
                                <%= @letrism.fill %>
                          </p>
                      <p>
              <strong>Stroke:</strong>
                                <%= @letrism.stroke %>
                          </p>
                      <p>
              <strong>Gallery:</strong>
                                <%= @letrism.gallery %>
                          </p>
                  </div>
      </div>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</section>