config/routes.rb
Rails.application.routes.draw do
  resources :letrisms, :equills
  
  devise_for :users, #path: "", :sign_out_via => [ :get ],
    :controllers => { 
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      sessions: 'users/sessions',
      unlocks: 'users/unlocks'
    }

  devise_scope :user do
    get ':lang/sign_up', to: 'users/registrations#new'
    get ':lang/sign_in', to: 'users/sessions#new'
    get ':lang/confirmation', to: 'users/confirmations#new'
    get ':lang/reset_password', to: 'users/passwords#new'
    get ':lang/unlock', to: 'users/unlocks#new'

    get 'crear-cuenta', to: 'users/registrations#new'
    get 'iniciar-sesion', to: 'users/sessions#new'
    get 'confirmar-cuenta', to: 'users/confirmations#new'
    get 'recuperar-cuenta', to: 'users/passwords#new'
    get 'desbloquear-cuenta', to: 'users/unlocks#new'
  end

  # admin
  get 'admin' => 'admin#index', as: :admin  
  namespace :admin do
    resources :users, :ogs, :videos, :images, :pages, :countries, :assets, :letrisms, :equills

    # blog
    get "blog" => "pages#blog", as: :blog
    # user
    get "profile" => "users#profile", as: :profile
    patch "update_profile" => "users#update_profile", as: :update_profile
  end
  
  # data
  get "manifest.json" => "site_info#manifest"

  # sitemaps
  get "sitemap" => "sitemaps#index"
  get "sitemap-static" => "sitemaps#static"
  get "images/sitemap" => "sitemaps#images"
  get "videos/sitemap" => "videos#sitemap"

  scope format: true, constraints: { format: /jpg|png|gif|webp|JPG|JPEG|jpeg/ } do
    get '/*anything', to: "errors#image_not_found"
  end

  scope format: true, constraints: { format: /js/ } do
    get '/*anything', to: "errors#script_not_found"
  end
  # Errors
  # https://guides.rubyonrails.org/v4.2.0/action_controller_overview.html#custom-errors-page
  match "404", via: :all, to: "errors#not_found", as: :not_found
  match "422", via: :all, to: "errors#unprocessable_entity", as: :unprocessable_entity
  match "500", via: :all, to: "errors#server_error", as: :server_error
  match 'offline', via: :all, to: 'errors#offline', as: :offline

  # App
  # root "static#page"
  root 'letrisms#index'

	# get 'manifiesto' => 'static_pages#manifest'
	# get 'galeria' => 'static_pages#gallery'
	# get 'contacto' => 'static_pages#contact'
	# get 'notebook' => 'letrisms#new'
	# get 'notebook/:id' => 'letrisms#new'

  get "mail" => "mailer#mail"
  # get ':lang' => 'static#page', as: :home
  get ':slug' => 'static#page', as: :page
  
end

app/models/country.rb
class Country < ApplicationRecord
    
    before_save { |obj| obj.send("#{:code}=", obj.send(:code).downcase) }
    before_save { |obj| obj.send("#{:alpha_2}=", obj.send(:alpha_2).downcase) }
    before_save { |obj| obj.send("#{:alpha_3}=", obj.send(:alpha_3).downcase) }
    before_save { |obj| obj.send("#{:continent}=", obj.send(:continent).downcase) }
    before_save { |obj| obj.send("#{:sub_continent}=", obj.send(:sub_continent).downcase) }
    
    after_initialize { |obj| obj.send("#{:continent}=", obj.send(:continent).titleize) }
    after_initialize { |obj| obj.send("#{:sub_continent}=", obj.send(:sub_continent).titleize) }

    validates_presence_of :name_en, :name_es, :code, :alpha_2, :continent, :alpha_3
    validates_uniqueness_of :alpha_2, :alpha_3

end

app/controllers/Admin/countries_controller.rb
class Admin::CountriesController < ApplicationController

  before_action :authenticate_admin!
  before_action :set_country, only: %i[ show edit update destroy ]

  layout "admin"

  # GET /countries
  def index
    @countries = Country.all
  end

  # GET /countries/1
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  def create
    @country = Country.new(country_params)

    if @country.save
      redirect_to admin_countries_url, notice: "Country ha sido creado."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /countries/1
  def update
    if @country.update(country_params)
      redirect_to admin_countries_url, notice: "Country ha sido actualizado."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /countries/1
  def destroy
    @country.destroy
    redirect_to admin_countries_url, notice: "Country ha sido eliminado."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.require(:country).permit(:continent, :sub_continent, :name_es, :name_en, :code, :alpha_2, :alpha_3, :active)
    end
end

app/views/admin/countries/_form.html.erb
<section class="w-full mx-auto">
  <%= form_for [:admin, country], local: true, html: { clas: "" } do |f| %>
  <%= render "admin/shared/errors", object: country %>
  <!-- .form/ -->
  <div class="grid grid-cols-2 gap-2">
    <%= f.label :name_es do %>
    <span class="truncated"><%= t(:name_es) %></span>
    <%= f.text_field :name_es, class: "", placeholder: t(:name_es), autofocus: true, required: true %>
    <% end %>
    <%= f.label :name_en do %>
    <span class="truncated"><%= t(:name_en) %></span>
    <%= f.text_field :name_en, class: "", placeholder: t(:name_en), required: true %>
    <% end %>
    <%= f.label :continent do %>
    <span class="truncated"><%= t(:continent) %></span>
    <%= f.select :continent, Country.pluck(:continent).uniq.sort.collect { |c| c.titleize }, {}, class: "", placeholder: t(:continent), required: true %>
    <% end %>
    <%= f.label :sub_continent do %>
    <span class="truncated"><%= t(:sub_continent) %></span>
    <%= f.select :sub_continent, Country.pluck(:sub_continent).uniq.sort.collect { |c| c.titleize }, {}, class: "", placeholder: t(:sub_continent) %>
    <% end %>
  </div>
  <div class="flex items-stretch justify-around space-x-2">
    <%= f.label :code do %>
    <span class="truncated">Código Teléfonico</span>
    <%= f.text_field :code, class: "", placeholder: t(:code), maxlength: 10, required: true %>
    <% end %>
    <%= f.label :alpha_2 do %>
    <span class="truncated"><%= t(:alpha_2) %></span>
    <%= f.text_field :alpha_2, class: " text-uppercase", placeholder: "XX", maxlength: 2, required: true %>
    <% end %>
    <%= f.label :alpha_3 do %>
    <span class="truncated"><%= t(:alpha_3) %></span>
    <%= f.text_field :alpha_3, class: " text-uppercase", placeholder: "XXX", maxlength: 3, required: true %>
    <% end %>
  </div>
  <!-- /.form -->
  <!-- .footer/ -->
  <footer class="w-full flex justify-between mt-2">
    <%= f.check_box :active, class: "sr-only peer" %>
    <%= f.label :active, class: "flex items-center text-dark-600 hover:text-dark-500 peer-checked:text-green-400 !cursor-pointer transition-colors" do %>
      <i class="fa-regular fa-circle-dot pr-1"></i>
      País Activo
    <% end %>
    <button class="btn btn-md"><i class="fas fa-save"></i> <%= t(:save) %></button>
  </footer>
  <% end %>
</section>

app/views/admin/countries/edit.html.erb
<% provide(:title, "Editando #{@country.name_es}") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium"><%= "Editando #{@country.name_es}" %></h1>
    <p class="mt-2 text-gray-500">Los países se administran para poder relacionarlos con registro de usuarios, proyectos, etc.</p>
  </div>
  <nav class="my-4 sm:flex-none">
    <%= link_to admin_countries_path, class: "btn danger" do %>
      <i class="fa-solid fa-arrow-left"></i> Regresar
    <% end %>
  </nav>
</header>

<%= render 'form', country: @country %>

app/views/admin/countries/index.html.erb
<% provide(:title, "Lista de #{t(:countries)}") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium">Lista de <%= t(:countries) %> <sup><%= Country.all.count %></sup></h1>
    <p class="mt-2 text-gray-500">Los países se administran para poder relacionarlos con registro de usuarios, proyectos, etc.</p>
  </div>
  <nav class="my-4 sm:flex-none">
    <%= link_to new_admin_country_path, class: 'btn' do %>
    <i class="fas fa-plus"></i> <%= "#{t(:new)} #{t(:country)}" %>
    <% end %>
  </nav>
</header>

<section class="my-8 flow-root">
  <table>
    <thead>
      <tr>
        <th>País</th>
        <th class="hidden lg:table-cell">Código Tel</th>
        <th class="hidden lg:table-cell">Códigos Alfa</th>
        <th><span class="sr-only">Eliminar</span></th>
      </tr>
    </thead>
    <tbody>
      <% @countries.each do |country| %>
      <tr>
        <td class="font-medium text-gray-300">
          <%= link_to country.name_en, edit_admin_country_url(country), class: "" %>
          <small class="block text-gray-500"><%= country.continent %><%= "/#{country.sub_continent.titleize}" if country.sub_continent.present? %></small>
        </td>
        <td class="hidden lg:table-cell"><%= country.code %></td>
        <td class="hidden lg:table-cell"><%= "#{country.alpha_2}/#{country.alpha_3}".upcase %></td>
        <td class="text-center">
          <%= link_to admin_country_path(country), method: :delete, class: "btn danger" , data: { confirm: "¿Estás seguro de eliminar este #{t(:country)}?" } do %>
          <i class='fas fa-trash'></i> Eliminar
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/admin/countries/new.html.erb
<% provide(:title, "#{t(:new)} #{t(:country)}") %>

<header class="flex flex-col-reverse md:items-center md:flex-row border-b border-white/5 py-4 sm:py-6 mb-2 md:mb-4">
  <div class="sm:flex-auto">
    <h1 class="leading-6 text-xl font-medium"><%= "#{t(:new)} #{t(:country)}" %></h1>
    <p class="mt-2 text-gray-500">Los países se administran para poder relacionarlos con registro de usuarios, proyectos, etc.</p>
  </div>
  <nav class="my-4 sm:flex-none">
    <%= link_to admin_countries_path, class: "btn danger" do %>
    <i class="fa-solid fa-arrow-left"></i> Regresar
    <% end %>
  </nav>
</header>

<%= render 'form', country: @country %>

app/views/admin/countries/show.html.erb
<% provide(:title, "country") %>

<header class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= "#{t(:detail)} de #{t(:country)}" %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right mt-2">
          <li class="breadcrumb-item">
            <%= link_to t(:countries), admin_countries_path %>
          </li>
          <li class="breadcrumb-item active">
            <%= "#{t(:detail)} de #{t(:country)}" %>
          </li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</header>

<section class="content">
  <!-- Default box -->
  <div class="card card-primary card-outline">
    <header class="card-header">
      <%= link_to edit_admin_country_url(@country), class: "btn btn-outline-primary btn-sm" do %>
        <i class="fas fa-pencil-alt"></i> Editar
      <% end -%>
      <%= link_to admin_country_path(@country), class: "btn btn-outline-danger btn-sm float-right", method: :delete, data: { confirm: "¿Estás seguro de eliminar este #{t(:country)}?" } do %>
        <i class="fa-solid fa-trash"></i> Eliminar
      <% end -%>
    </header>
    <div class="card-body">
      <div class="row">
        <div class="col-12">
                      <p>
              <strong>Continent:</strong>
                                <%= @country.continent %>
                          </p>
                      <p>
              <strong>Sub continent:</strong>
                                <%= @country.sub_continent %>
                          </p>
                      <p>
              <strong>Name es:</strong>
                                <%= @country.name_es %>
                          </p>
                      <p>
              <strong>Name en:</strong>
                                <%= @country.name_en %>
                          </p>
                      <p>
              <strong>Code:</strong>
                                <%= @country.code %>
                          </p>
                      <p>
              <strong>Alpha 2:</strong>
                                <%= @country.alpha_2 %>
                          </p>
                      <p>
              <strong>Alpha 3:</strong>
                                <%= @country.alpha_3 %>
                          </p>
                      <p>
              <strong>Active:</strong>
                                <%= @country.active %>
                          </p>
                  </div>
      </div>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</section>