config/routes.rb
Rails.application.routes.draw do
  resources :letrisms, :equills
  
  devise_for :users, #path: "", :sign_out_via => [ :get ],
    :controllers => { 
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      sessions: 'users/sessions',
      unlocks: 'users/unlocks'
    }

  devise_scope :user do
    get ':lang/sign_up', to: 'users/registrations#new'
    get ':lang/sign_in', to: 'users/sessions#new'
    get ':lang/confirmation', to: 'users/confirmations#new'
    get ':lang/reset_password', to: 'users/passwords#new'
    get ':lang/unlock', to: 'users/unlocks#new'

    get 'crear-cuenta', to: 'users/registrations#new'
    get 'iniciar-sesion', to: 'users/sessions#new'
    get 'confirmar-cuenta', to: 'users/confirmations#new'
    get 'recuperar-cuenta', to: 'users/passwords#new'
    get 'desbloquear-cuenta', to: 'users/unlocks#new'
  end

  # admin
  get 'admin' => 'admin#index', as: :admin  
  namespace :admin do
    resources :users, :ogs, :videos, :images, :pages, :countries, :assets, :letrisms, :equills

    # blog
    get "blog" => "pages#blog", as: :blog
    # user
    get "profile" => "users#profile", as: :profile
    patch "update_profile" => "users#update_profile", as: :update_profile
  end
  
  # data
  get "manifest.json" => "site_info#manifest"

  # sitemaps
  get "sitemap" => "sitemaps#index"
  get "sitemap-static" => "sitemaps#static"
  get "images/sitemap" => "sitemaps#images"
  get "videos/sitemap" => "videos#sitemap"

  scope format: true, constraints: { format: /jpg|png|gif|webp|JPG|JPEG|jpeg/ } do
    get '/*anything', to: "errors#image_not_found"
  end

  scope format: true, constraints: { format: /js/ } do
    get '/*anything', to: "errors#script_not_found"
  end
  # Errors
  # https://guides.rubyonrails.org/v4.2.0/action_controller_overview.html#custom-errors-page
  match "404", via: :all, to: "errors#not_found", as: :not_found
  match "422", via: :all, to: "errors#unprocessable_entity", as: :unprocessable_entity
  match "500", via: :all, to: "errors#server_error", as: :server_error
  match 'offline', via: :all, to: 'errors#offline', as: :offline

  # App
  # root "static#page"
  root 'letrisms#index'

	# get 'manifiesto' => 'static_pages#manifest'
	# get 'galeria' => 'static_pages#gallery'
	# get 'contacto' => 'static_pages#contact'
	# get 'notebook' => 'letrisms#new'
	# get 'notebook/:id' => 'letrisms#new'

  get "mail" => "mailer#mail"
  # get ':lang' => 'static#page', as: :home
  get ':slug' => 'static#page', as: :page
  
end

app/controllers/Admin/images_controller.rb
class Admin::ImagesController < ApplicationController

  before_action :authenticate_admin!
  before_action :set_image, only: %i[ show edit update destroy ]
  layout "admin"

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.create(set_image_params(image_params))
    if image_params[:file].present?
      @image.file = image_params[:file]
    end
    if @image.save
      redirect_to admin_image_path(@image), notice: "La imagen ha sido creada."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    # si la imagen cambia, debe reasignarse slug para no dejar cache
    if image_params[:file].present?
      @image.update(file: image_params[:file], slug: @image.safe_title(image_params[:title]))
      @image.file.recreate_versions!
    elsif image_params[:title] != @image.title
      #Si se actualiza el título la imagen se debe reprocesar para coincidir con el título
      @image.update(slug: @image.safe_title(image_params[:title]))
      @image.file.recreate_versions!
    end
    if @image.update(set_image_params(image_params))
      redirect_to "/admin/images", notice: "La imagen #{@image.title} ha sido actualizada."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /images/1
  def destroy
    @image.destroy
    redirect_to admin_images_url, notice: "La imagen ha sido eliminada."
  end

  private

    def set_image_params(_params)
      mime, extension = ""
      if _params['file'].present?
        mime = _params['file'].content_type
        extension = mime.split('/')[1]
      else
        extension = @image.extension
        mime = @image.mime_type
      end
      return {
        title: _params['title'],
        alt: _params['alt'],
        bg: _params['bg'],
        color: _params['color'],
        rainbow: _params['rainbow'],
        extension: extension,
        mime_type: mime
      }
    end

    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:title, :file, :alt, :bg, :color, :rainbow)
    end
end

app/helpers/images_helper.rb
module ImagesHelper

    def img_dimensions(img)
        `identify -format "%wx %h" #{Rails.public_path}#{img}`.split(/x/).map{|dim| dim.to_i }
    end
    
    def file_size(img)
        size = File.size("#{Rails.public_path}#{img}").to_f
        "#{(size / 1024000).round(2)}mb"
    end

    def video_info(video_url)
        FFMPEG::Movie.new(File.join Rails.root, 'public', video_url)
    end

end

app/views/admin/images/_form.html.erb
<style>
.palette-color-btn {
  width: 42px;
  height: 42px;
  border-radius: 50%;
  overflow: hidden;
  display: inline-block;
  margin: 5px;
  background-color: currentColor;
  border: 3px solid currentColor;
}
.palette-color-btn:hover,
.palette-color-btn.active {
  border: 3px solid green;
}
.palette-container {
  width: 100%;
  text-align: center;
  display: flex;
  flex-wrap: wrap;
  align-content: space-between;
  align-items: flex-end;
  flex-direction: row;
  justify-content: center;
}
label[for='image_file'] {
  width: 100%;
}
#img-preview-file {
  object-position: center;
  object-fit: contain;
  max-height: 300px;
  width: 100%;
}

#colors-container {
  border-radius: 1em;
  padding-top: 1em;
  text-align: center;
  --bg-color: <%= @image.bg %>;
  --color: <%= @image.color %>;
  background: linear-gradient(0deg, var(--bg-color) 0%, var(--color) 100%);
  <%# background: var(--bg-color); %>
  color: var(--color);
  margin-bottom: 1em;
}
#colors-container input{
  background: inherit;
  color: inherit;
}
</style>
<section class="content">
  <%= form_for [:admin, image], local: true, html: { class: "row" } do |f| %>
    <div class="col-md-12">
      <!-- .card/ -->
      <div class="card card-primary card-outline">
        <!-- .card-body/ -->
        <div class="card-body row">
          <%= render "admin/shared/errors", object: image %>
         <div class="col-md-12">
            <div class="row" id="colors-container">
              <div class="form-group col-md-12">
                <%= f.label :file do %>
                  <%= image_tag image.file.present? ? image.file.vga.url : '', id: "img-preview-file" %>
                  <br>Imagen
                <% end %>
                <%= f.file_field :file, class: "form-control input-img", data: { target: "#img-preview-file" }, accept: "image/*" %>
              </div>
              <%= f.hidden_field :rainbow, class: "form-control" %>
              <div class="form-group col-md-6">            
                <div class="palette-container" id="bg-palette">
                  <% @image.palette.each do |hex| %>
                      <a href="<%= hex %>" class="palette-color-btn <%= 'active' if hex == @image.bg %>" style="color: <%= hex %>">
                        <%= hex %>
                      </a>
                    <% end %>
                </div>
                <%= f.label :bg, "Background" %>
                <%= f.hidden_field :bg %>
              </div>
              <div class="form-group col-md-6">            
                <div class="palette-container" id="color-palette">
                  <% @image.palette.each do |hex| %>
                      <a href="<%= hex %>" class="palette-color-btn <%= 'active' if hex == @image.color %>" style="color: <%= hex %>">
                        <%= hex %>
                      </a>
                    <% end %>
                </div>
                <%= f.label :color, "Color" %>
                <%= f.hidden_field :color %>
              </div>
            </div>
          </div>

          <div class="form-group col-md-6">
            <%= f.label :title, "Título" %>
            <%= f.text_field :title, class: "form-control", placeholder: "Título", required: true %>
          </div>

          <div class="form-group col-md-6">
            <%= f.label :alt, "Texto alternativo" %>
            <%= f.text_field :alt, class: "form-control", placeholder: "Texto alternativo", required: true %>
          </div>

        </div>
        <!-- /.card-body -->
        <!-- .card-footer/ -->
        <footer class="card-footer text-right">
          <button class="btn btn-outline-primary mt-2 mb-2 btn-sm"><i class="fas fa-save"></i> <%= t(:save) %></button>
        </footer>
        <!-- /.card-footer -->
      </div>
      <!-- /.card -->
    </div>
  <% end %>
</section>

app/views/admin/images/_index.html.erb
<% if images.empty? %>
    <div class="col-md-12 text-center mt-4">
        <p>Aún no se ha agregado ninguna imagen</p>
    </div>
<% else %>
    <% images.each do |image| %>
    <div class="col-6 col-sm-4 col-md-3 col-xl-2">
        <div class="row">
          <%= link_to admin_image_url(image), class: "col-12 p-0", style: "background-color: #{image.bg};", title: image.title do %>
          <%= image_tag image.file.thumb.url, alt: image.alt, width: 240, height: 240 %>
          <ul class="palette">
              <% image.palette.each do |hex| %>
                <li style='background-color: <%= hex %>;'></li>
              <% end %>
          </ul>
          <% end %>
          <%= link_to edit_admin_image_url(image), class: "btn col-6 btn-outline-info btn-sm" do %>
            <i class="fas fa-pencil-alt"></i> Editar
          <% end %>
          <%= link_to admin_image_url(image), method: :delete, class: "btn col-6 btn-outline-danger btn-sm" , data: { confirm: "¿Estás seguro de eliminar este imagen? (#{image.title})" } do %>
            <i class='fas fa-trash'></i> Eliminar
          <% end %>
        </div>
    </div>
    <% end %>
<% end %>

<style>
#img-grid a {
  display: inline-block;
  border: 1px solid #dbdbdb;
  border-radius: 6px;
  width: 100%;
  text-align: center;
}
#img-grid a img {
  width: 100%%;
  max-width: 240px;
  max-height: 240px;
  object-fit: cover;
  object-position: center;
}
ul.palette {
  padding: 0;
  margin: 0;
  width: 100%;
  list-style: none;
  display: flex;
}
ul.palette  li {
  width: 100%;
  height: 1em;
}
</style>

app/views/admin/images/_modal.html.erb
<style>
.image-item {
  opacity: 0.75;
  display: inline-block;
  border-radius: 5px;
}
.image-item.active,
.image-item:hover {
  opacity: 1;
}
</style>
<% @images = Image.all %>
<div class="modal fade" id="images-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Galería de imágenes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body row">
        <% if @images.empty? %>
        <div class="col-md-12 text-center mt-4">
          <p>Aún no se ha agregado ninguna imagen</p>
        </div>
        <% else %>
        <% @images.each do |image| %>
        <div class="col-6 col-sm-4 col-md-3">
          <%= link_to "#", class: "m-2 w-full image-item", style: "background-color: #{image.bg};", data: { preview: image.file.thumb.url, id: image.id, title: "#{image.alt}" }, title: image.title do %>
            <%= image_tag image.file.thumb.url, alt: image.alt, width: 240 %>
          <% end %>
        </div>
        <% end %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="select-img-btn"><i class="fa-solid fa-check"></i> Seleccionar</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/images/_select_img.html.erb
<div class="input-group col-md-12 img-container">
    <%= image_tag (f.object.image.nil? ? "/static/img-not-found.png" : f.object.image.file.vga.url), id: "image-preview-#{idx}" %>
    <div class="input-group-prepend">
        <span class="input-group-text">Imagen</span>
    </div>
    <input type="text" class="form-control"
      value="<%= f.object.image.nil? ? "Sin imagen" : "#{f.object.image.alt}" %>"
      readonly id="label-image-<%= idx %>">
    <div class="input-group-append">
      <a href="#" class="btn btn-primary input-group-text search-image-btn" data-toggle="modal" data-preview="#image-preview-<%= idx %>"
        data-target="#images-modal" data-label="#label-image-<%=idx%>">
        <%= f.hidden_field :image_id %><i class="fa-solid fa-image"></i> 
      </a>
    </div>
  </div>

app/views/admin/images/create.js.erb
$("#img-preview-file").attr("src","")
$("#image_title").val("")
$("#image_alt").val("")

app/views/admin/images/edit.html.erb
<% provide(:title, "Editando Imagen") %>

<header class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Editando Imagen</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right mt-2">
          <li class="breadcrumb-item">
            <%= link_to t(:images), admin_images_path %>
          </li>
          <li class="breadcrumb-item active">
            Editando Imagen
          </li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</header>

<%= render 'form', image: @image, remote: false %>

app/views/admin/images/index.html.erb
<% provide(:title, "Lita de imágenes") %>

<!-- Content Header (Page header) -->
<header class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-12">
        <ol class="breadcrumb float-sm-right mt-2">
          <li class="breadcrumb-item active"><%= t(:images) %></li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</header>
<!-- Main content -->
<section class="content">
  <!-- Default box -->
  <div class="card card-primary card-outline">
    <header class="card-header">
      <h1 class="card-title">Galería de imagenes</h1>
      <%= link_to new_admin_image_path, class: 'btn btn-outline-primary btn-sm float-right' do %>
        <i class="fas fa-plus"></i>
        Nueva Imagen
      <% end %>
    </header>
    <div class="card-body row" id="img-grid">
      <%= render "admin/images/index", images: @images %>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->

</section>
<!-- /.content -->

app/views/admin/images/new.html.erb
<% provide(:title, "Nueva Imagen") %>

<header class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Nueva Imagen</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right mt-2">
          <li class="breadcrumb-item">
            <%= link_to t(:images), admin_images_path %>
          </li>
          <li class="breadcrumb-item active">
            Nueva Imagen
          </li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</header>

<%= render 'form', image: @image, remote: false %>

app/views/admin/images/show.html.erb
<% provide(:title, "Imagen - #{@image.title}") %>

<header class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Detalle de imagen</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right mt-2">
          <li class="breadcrumb-item">
            <%= link_to t(:images), admin_images_path %>
          </li>
          <li class="breadcrumb-item active">
            Detalle de imagen
          </li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</header>
<style>
ul.palette {
  padding: 0;
  margin: 0;
  width: 100%;
  list-style: none;
  display: flex;
}
ul.palette  li {
  width: 100%;
  height: 2em;
}
picture {
  max-width: 600px;
  display: block;
  margin: 0 auto;
}
</style>
<section class="content">
  <!-- Default box -->
  <div class="card card-primary card-outline">
  <header class="card-header">
      <%= link_to edit_admin_image_path(@image), class: "btn btn-outline-primary btn-sm" do %>
        <i class="fa-solid fa-pencil"></i> Editar
      <% end -%>
      <%= link_to admin_image_path(@image), class: "btn btn-outline-danger btn-sm float-right", method: :delete, data: { confirm: "¿Estás seguro de eliminar esta imagen}?" } do %>
      <i class="fa-solid fa-trash"></i> Eliminar
      <% end -%>
    </header>
    <div class="card-body" style="background-color: <%= @image.bg %>; color: <%= @image.color %>;">
      <div class="row">
        <div class="col-12">
            <h1><%= @image.title %></h1>
            <p><%= @image.alt %></p>
            <picture class="w-full">
              <source type="image/webp" media="(max-width: 640px)" srcset="<%= asset_url(@image.file.vga_webp.url) %>" />
              <source type="<%= @image.mime_type %>" media="(max-width: 640px)" srcset="<%= asset_url(@image.file.vga.url) %>" />
              <source type="image/webp" media="(max-width: 960px)" srcset="<%= asset_url(@image.file.qhd_webp.url) %>" />
              <source type="<%= @image.mime_type %>" media="(max-width: 960px)" srcset="<%= asset_url(@image.file.qhd.url) %>" />
              <source type="image/webp" media="(max-width: 1280px)" srcset="<%= asset_url(@image.file.hd_webp.url) %>" />
              <source type="<%= @image.mime_type %>" media="(max-width: 1280px)" srcset="<%= asset_url(@image.file.hd.url) %>" />
              <source type="image/webp" media="(max-width: 1920px)" srcset="<%= asset_url(@image.file.fhd_webp.url) %>" />
              <source type="<%= @image.mime_type %>" media="(max-width: 1920px)" srcset="<%= asset_url(@image.file.fhd.url) %>" />
              <img src="<%= asset_url(@image.file.thumb.url) %>" alt="<%= @image.alt %>"/>
          </picture>
          <!-- palette/.  -->
          <ul class="palette">
            <% @image.palette.each do |hex| %>
              <li style='background-color: <%= hex %>;'></li>
            <% end %>
          </ul>
          <!-- /.palette  -->
          <!-- versions info/.  -->
          <table class="table table-sm table-hovered text-center">
            <thead>
              <tr>
                <th class='text-left'>Version</th>
                <th>Screen</th>
                <th>ImgDimensions</th>
                <th>.<%= @image.extension %></th>
                <th>.webp</th>
              </tr>
            </thead>
            <tbody>
              <!-- quad_hd_webp/. -->
              <tr>
                <td class='text-left'>Quad HD</td>
                <td>2560x1440</td>
                <td><%= img_dimensions(@image.file.quad_hd.url) %></td>
                <td>
                  <%= link_to asset_url(@image.file.quad_hd.url), title: "Quad HD", target: "_blank" do %>
                    <%= file_size(@image.file.quad_hd.url) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to asset_url(@image.file.quad_hd_webp.url), title: "Quad HD", target: "_blank" do %>
                    <%= file_size(@image.file.quad_hd_webp.url) %>
                  <% end %>
                </td>
              </tr>
              <!-- /.fullhd. -->
              <!-- fullhd/. -->
              <tr>
                <td class='text-left'>FullHD</td>
                <td>1920x1080</td>
                <td><%= img_dimensions(@image.file.fhd.url) %></td>
                <td>
                  <%= link_to asset_url(@image.file.fhd.url), title: "FullHD", target: "_blank" do %>
                    <%= file_size(@image.file.fhd.url) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to asset_url(@image.file.fhd_webp.url), title: "FullHD", target: "_blank" do %>
                    <%= file_size(@image.file.fhd_webp.url) %>
                  <% end %>
                </td>
              </tr>
              <!-- /.fullhd. -->
              <!-- HD/. -->
              <tr>
                <td class='text-left'>HD</td>
                <td>1280x720</td>
                <td><%= img_dimensions(@image.file.hd.url) %></td>
                <td>
                  <%= link_to asset_url(@image.file.hd.url), title: "HD", target: "_blank" do %>
                    <%= file_size(@image.file.hd.url) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to asset_url(@image.file.hd_webp.url), title: "HD", target: "_blank" do %>
                    <%= file_size(@image.file.hd_webp.url) %>
                  <% end %>
                </td>
              </tr>
              <!-- /.HD. -->
              <!-- qhd/. -->
              <tr>
                <td class='text-left'>QHD</td>
                <td>960x540</td>
                <td><%= img_dimensions(@image.file.qhd.url) %></td>
                <td>
                  <%= link_to asset_url(@image.file.qhd.url), title: "QHD", target: "_blank" do %>
                    <%= file_size(@image.file.qhd.url) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to asset_url(@image.file.qhd_webp.url), title: "QHD", target: "_blank" do %>
                    <%= file_size(@image.file.qhd_webp.url) %>
                  <% end %>
                </td>
              </tr>
              <!-- /.qhd. -->
              <!-- vga/. -->
              <tr>
                <td class='text-left'>VGA</td>
                <td>640x480</td>
                <td><%= img_dimensions(@image.file.vga.url) %></td>
                <td>
                  <%= link_to asset_url(@image.file.vga.url), title: "VGA", target: "_blank" do %>
                    <%= file_size(@image.file.vga.url) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to asset_url(@image.file.vga_webp.url), title: "VGA", target: "_blank" do %>
                    <%= file_size(@image.file.vga_webp.url) %>
                  <% end %>
                </td>
              </tr>
              <!-- /.vga. -->
              <!-- thumb/. -->
              <tr>
                <td class='text-left'>Thumb</td>
                <td>240x</td>
                <td><%= img_dimensions(@image.file.thumb.url) %></td>
                <td>
                  <%= link_to asset_url(@image.file.thumb.url), title: "VGA", target: "_blank" do %>
                    <%= file_size(@image.file.thumb.url) %>
                  <% end %>
                </td>
                <td>-</td>
              </tr>
              <!-- /.vga. -->
          </table>
          <!-- /.versions info  -->
        </div>
      </div>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</section>